version: "3.9"
   
services:
  db:
    image: postgres:13-alpine
    restart: always
    volumes:
      - grog_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_PASSWORD=${DB_PASSWORD}

volumes:
    grog_data:
